### ISSUE TITLE
[Feature] Adding the speed based on the analog volt signal

### ISSUE THREAD

**Issue by Henry-Sir** [rsnodgrass/hass-lunos#6]
I have implemented the "smart switch"  with the help of a Shelly UNI 
(https://shelly.cloud/products/shelly-uni-smart-home-automation-device/ https://shelly.cloud/knowledge-base/devices/shelly-uni/).

The advantage of the Shelly UNI is:
- very small
- supply voltage DC 12 - 36V = can be supplied directly from the Lunos voltage (12V)
- no relays are needed, hand switch and LUNOS controller can be connected directly 
- an analog input (0 -12 / 0 -30 VCD), so the regulation voltage (0 - 10V) can be measured by the Lunos controller.

So my question, can the analog volt signal be integrated to show the actual speed of the fan?

I know that the voltage signal depends on the current mode of the controller:

e2: 0 - 5 V = exhaust air
       5 - 10 V = supply air

ra: 0 - 10 V = exhaust air

### **Lunos e2:**
![image](https://user-images.githubusercontent.com/75314095/154559478-f3d3ed57-f2c2-4dc8-94f5-8ae845362857.png)

![image](https://user-images.githubusercontent.com/75314095/154559689-887f23e1-afa8-45f1-a1df-fabcedccb1cd.png)

 
  
  

### **Lunos RA-15-60 (5/UNI-FT - Humidity control is ON)**

![image](https://user-images.githubusercontent.com/75314095/154559918-ab83ce36-46bc-4011-a535-9647adb58203.png)

![image](https://user-images.githubusercontent.com/75314095/154560239-615cef5d-5278-439a-bddf-b4ea0820c7b8.png)

**Comment by rsnodgrass** [comment]
Fantastic work!  I was hoping someone would implement an alternative hardware controller someday, since there are features I'd love to add to my LUNOS system. 

Notably:

* turn on specific LUNOS units to exhaust only mode (while the others continue to cycle) when there is high VOC/PM2 detected in specific rooms

* set the LUNOS unit near a fireplace to slow speed/intake only mode (while the others continue to cycle) when a fire is going to provide a constant supply of fresh air (and reduce the chance of backdraft on windy days)

**Comment by rsnodgrass** [comment]
Regarding your question:

"can the analog volt signal be integrated to show the actual speed of the fan?"

I'm not sure what you are asking.  I am sure you could do this, but what were you envisioning as far as where this would be implemented?
